### ISSUE TITLE
i'm sorry this is not a real issue!

### ISSUE THREAD

**Issue by harakiwi** [ben-burns/imgur-gifv#1]
see title, BUT i don't know any other way to write a developer on GitHub.

I **LOVE** you addon, it's so convenient to load gifv (faster loading times ffs ...)

i wondered if it's possible to re-adjust your code and write myself a little addon that does the same thing on **gfycat (A)** and something different on google image service **Picasa/Google Photos (B)**

A) some people post the GIF version of gfycat links, i want my browser to load the default link without extensions OR the webm version

B) i'm sharing most of my screenshots and photos via googles Picasa tool, but the webservice shows the image depending on my monitors resolution.
Every hotlink-URL includes a part that represents this number and if changed to "0" it will show me the whole file in it's uploaded resolution.
i.e. https://lh3.googleusercontent.com/ _a lot of random numbers_ /s1280-Ic42/  _and it's filename.extension_. 
In this case it downscales the picture on my 1080p monitor to fit inside the browser window
**s1280** changed to **s0** will do the trick.

**I'm not expection you to rewrite your addon!** Don't missunderstand me, i'm just bad at coding and wondered about this feature for a few months.

Happy holidays anyways! ;D

**Comment by ben-burns** [comment]
A) I believe I added this but haven't pushed it to git, yet.  I will check shortly, as I haven't touched the code for a few months.
B) Not sure exactly how Picasa works, but if you send me some images to test (5-10 images would be helpful), I can see about including it, given the example you provided (s1280 -> s0).

**Comment by harakiwi** [comment]
wow that was fast!

A) would be great to avoid those annoying loadtimes, realizing 50% into it why it's taking so long. Crying inside... loading xxxMB GIFs ... why ...should we have to?

B) easy! i'll add some older screenshots taken on a **smaller monitor**, **smartphone photos** (4:3) or taken in **portrait mode** resulting in smaller res pictures, resulting in other/smaller "s-xxx" numbers

these are all pictures uploaded to google and accessed via https://picasaweb.google.com/ (my personal google account). I'm not sure about links from Google Photos (don't like the site).

edit: a final notice! the filename and extension is not necessary! cutting links down to "Ic42/" is okay 
and will work fine\* too. The slash **/** in Ic42**/** is necessary!
*(but some image-tools in BB code or [IMG] links might break using a link to a picture without an extension) 

http://pastebin.com/vdLjZNCL

(i've set an expiration date to 1 month, because i'm not sure about posting this stuff public to everyone)

**Comment by ben-burns** [comment]
I just pushed the latest version (1.2), which includes Gfycat support.  However, after further thought, Picasa support is not something that I feel will benefit all users, currently.  Thus, I have not included it in this update.

I will, however, provide you with some guidance:
- Fork this project
- Edit lib/main.js to include the following:

``` javascript
// Picasa
pageMod.PageMod({
    contentScriptWhen: 'start', // Don't wait until the page finishes loading
    include: [/(http(s)?:\/\/.*)\.googleusercontent\.com\/.{12}\/.{11}\/.{11}\/.{11}\/.*\/.*/], // Make sure we are looking at an image from googleusercontent.com
    contentScriptFile: [self.data.url("picasa.js")] // picasa.js when we have a match
});
```
- Create data/picasa.js, and include the following:

``` javascript
var contentType = document.contentType; // page-mod offers no type support, so we need to use document.contentType
var contentTypeRegEx = /image\/.*/;

if(contentTypeRegEx.test(contentType)) { // Make sure the content type is an image of some type
    var urlPath     = document.location.href.split('/'); // Split the URL into an array
    var urlRes      = urlPath[7]; // URL path containing s*
    var urlResValue = /\d+/; // Regex for the value of s*

    // Check if the value of s* isn't already 0 (s0-xxxx)    
    if(urlRes.match(urlResValue) != 0) {
        window.stop(); // Stop loading the page

        var urlResEnd = urlRes.match(/(?:s\d+-)(.*)/)[1]; // Find the string after s*- so we can add it to s0-, below
        var newUrlRes = "s0-" + urlResEnd; // s0 for higher resolution
        var domain  = location.origin // *googleusercontent.com
        var newUrlPath = "/" + urlPath[3] + "/" + urlPath[4] + "/" + urlPath[5] + "/" + urlPath[6] + "/" + newUrlRes + "/" + urlPath[8]; // Stitch the URL path back together

        location.replace(domain + newUrlPath); // Redirect the user
    }
}
```
- Build and test the extension (using [JPM](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm))

**Comment by harakiwi** [comment]
Thank you so much! Will try my first baby-steps on GitHub. I it's so much easier to post screenshots or photos / travel logs and link to original-size picture and let the forums .js resize it on-the-fly :)

Hope you too*\* had a few days off, between the stressed out "holidays" and a late Happy New Year!

**( i'm back from visiting my family (and getting visted alot). Time to answer some Emails ;D )

**Comment by ben-burns** [comment]
Closing out this issue.  Thanks for your support and let me know if you have any other issues.
